spring:
  profiles:
    active: cloud
---

spring:
  profiles: cloud
  cloud:
    config:
      discovery:
        enabled: true
server:
  port: 13000
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
eureka:
  instance:
    hostname: payu
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://registry.dstv.com/eureka/

---

spring:
  profiles: development
server:
  port: 13000
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
    
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
