spring:
  profiles:
    active: cloud
---

spring:
  profiles: cloud
  cloud:
    config:
      discovery:
        enabled: true
server:
  port: 13000
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
eureka:
  instance:
    hostname: payu
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://registry.dstv.com/eureka/

---

spring:
  profiles: development
server:
  port: 13000
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
    
payu:
  client:
    posId: 145227
    secondKey: 13a980d4f851f3d9a1cfc792fb1f5e50
    clientSecret: 12f071174cb7eb79d4aac5bc2f07563f
    authorizationUri: https://secure.payu.com/
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://secure.payu.com/
    
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
